apps/inventory/urls.py
from django.conf.urls import url, include
from apps.inventory.views import index, Create_value, Maintainer_item, Movement_maint, Movement_detail
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    url(r'^movement/(?P<value>\w+)/(?P<code>\d+)/$', login_required(Movement_maint), name='movement'),
    url(r'^movement_detail/(?P<code>\d+)/$', login_required(Movement_detail), name='movement_detail'),
    url(r'^(?P<value>\w+)/create/$', login_required(Create_value), name="create_value"),
    url(r'^item/maintainer/(?P<value>\w+)/(?P<code>\d+)/$', login_required(Maintainer_item), name='maintainer_item'),
]

prevex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='index')),
    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^screen/', include('apps.screen.urls', namespace='screen')),
    url(r'^inventory/', include('apps.inventory.urls', namespace='inventory')),
    url(r'^binnacle/', include('apps.binnacle.urls', namespace='binnacle')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]
urlpatterns += [
    url(r'^accounts/login/', login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/inventory/models.py
from django.db import models

# Create your models here.
class Location(models.Model):
    title = models.CharField(null=False, max_length=50)
    def __str__(self):
        return '{}'.format(self.title)

class Group(models.Model):
    title = models.CharField(null=False, max_length=50)
    def __str__(self):
        return '{}'.format(self.title)

class State(models.Model):
    title = models.CharField(null=False, max_length=50)
    def __str__(self):
        return '{}'.format(self.title)

class Item(models.Model):
    code = models.IntegerField(null=False, unique=True)
    description = models.CharField(max_length=50)
    group = models.ForeignKey(Group, null=False, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.code)

class Movement(models.Model):
    code = models.ForeignKey(Item, null=False, blank=True, on_delete=models.CASCADE)
    state = models.ForeignKey(State, null=False, blank=True, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, null=False, blank=True, on_delete=models.CASCADE)
    stock = models.IntegerField(null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{}'.format(self.code)

apps/inventory/forms.py
from django import forms
from apps.inventory.models import Group, State, Location, Item, Movement

class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = [
            'title'
        ]
        labels = {
            'title':'Title'
        }
        widgets = {
            'title' :forms.TextInput(attrs={'class':'form-control'}),
        }

class StateForm(forms.ModelForm):

    class Meta:
        model = State
        fields = [
            'title'
        ]
        labels = {
            'title':'Title'
        }
        widgets = {
            'title' :forms.TextInput(attrs={'class':'form-control'}),
        }

class LocationForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = [
            'title'
        ]
        labels = {
            'title':'Title'
        }
        widgets = {
            'title' :forms.TextInput(attrs={'class':'form-control'}),
        }

class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = [
            'title'
        ]
        labels = {
            'title':'Title'
        }
        widgets = {
            'title' :forms.TextInput(attrs={'class':'form-control'}),
        }

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = [
            'code',
            'description',
            'group'
        ]
        labels = {
            'code' : 'Code',
            'description': 'Description',
            'group': 'Group',
        }
        widgets = {
            'code' :forms.TextInput(attrs={'class':'form-control'}),
            'description' :forms.TextInput(attrs={'class':'form-control'}),
            'group' :forms.Select(attrs={'class':'form-control'}),
        }

class MovementForm(forms.ModelForm):

    class Meta:
        model = Movement
        fields = [
            'code',
            'state',
            'location',
            'stock'
        ]
        labels = {
            'code' : 'Code',
            'state': 'State',
            'location': 'Location',
            'stock': 'Stock'
        }
        widgets = {
            'code' :forms.Select(attrs={'class':'form-control'}),
            'state' :forms.Select(attrs={'class':'form-control'}),
            'location' :forms.Select(attrs={'class':'form-control'}),
            'stock' :forms.TextInput(attrs={'class':'form-control'}),
        }

apps/inventory/views.py
from django.shortcuts import render, redirect
from apps.inventory.models import Movement, Location, State, Group, Item
from apps.inventory.forms import GroupForm, StateForm, LocationForm, ItemForm, MovementForm
from django.db.models import Sum
from apps.user.views import Admin


# Create your views here.

def index(request):
    model_item = Item.objects.all()
    data = {}
    data['admin'] = Admin(request)
    data['inventory'] = 'active'
    data['title'] = 'Inventario'
    data['data'] = {}
    for items in model_item:
        items.sum = 0
        model_move = Movement.objects.filter(code=items)
        total = model_move.aggregate(Sum('stock'))
        if total['stock__sum']:
            items.sum = str(total['stock__sum'])
        else:
            items.sum = '0'

        data['data'][items]={'code': items.code,
                       'sum': items.sum,
                        'description': items.description,
                       'group': items.group.title}
    return render(request, 'inventory/index.html', data)


def Movement_maint(request, value, code):
    data = {}
    data['admin'] = Admin(request)
    data['title'] = 'Inventario'
    data['inventory'] = 'active'
    if value == 'create':
        int_code = int(code)
        if code == '0':
            data['item'] = Item.objects.all()
            data['data'] = Movement.objects.all().order_by("-id")[:5]
        elif code != '0':
            data['select']= Item.objects.get(code = int_code)
            csl = True
            id_ = Item.objects.get(code=int_code)
            data['data'] = Movement.objects.filter(code = id_.id).order_by("-id")[:5]

        data['state'] = State.objects.all()
        data['location'] = Location.objects.all()
        data['form'] = MovementForm()
        data['code'] = code

        if request.method == 'POST':
            form = MovementForm(request.POST)
            if form.is_valid():
                form.save()

            return redirect('inventory:movement', 'create', code)

        #data['option_'] = MovementForm()
    return render(request, 'inventory/movement.html', data)


def Create_value(request, value):
    data = {}
    data['admin'] = Admin(request)
    data['title'] = 'Inventario'
    data['group'] = {'model': Group.objects.all().order_by('title'), 'form': GroupForm, 'title': 'Grupo', 'inventory': 'active'}
    data['state'] = {'model': State.objects.all(), 'form': StateForm, 'title': 'Estado', 'inventory': 'active'}
    data['location'] = {'model': Location.objects.all(), 'form': LocationForm, 'title': 'Ubicacion', 'inventory': 'active'}
    if request.method == 'POST':
        form = data[value]['form'](request.POST)
        if form.is_valid():
            form.save()
            return redirect('inventory:maintainer_item', 'create', '0')

    return render(request, 'inventory/create_value.html', data[value])


def Maintainer_item(request, value, code):
    data = {
        'data' : Item.objects.all(),
        'form' : ItemForm(),
        'group': Group.objects.all(),
        'option': 'Mantenedor de items'
    }
    data['admin'] = Admin(request)
    data['inventory'] = 'active'
    data['title'] = 'Inventario'
    if value == 'create':
        data['model'] = Item.objects.all()
        if request.method == 'POST':
            form = ItemForm(request.POST)
            if form.is_valid():
                form.save()

                return redirect('inventory:maintainer_item', 'create', '0')
            else:
                print(form.is_valid())
                print(form.errors)
    elif value == 'edit':
        code_=str(code)
        item = Item.objects.get(code=code_)
        data['form'] = ItemForm(instance=item)
        data['edit'] = Item.objects.get(code=code_)
        if request.method == "POST":
            form = ItemForm(request.POST, instance=item)
            if form.is_valid():
                form.save()
            return redirect('inventory:maintainer_item', 'create', '0')

    return render(request, 'inventory/maintainer_item.html', data)

def Movement_detail(request, code):
    int_code = int(code)
    id_ = Item.objects.get(code=int_code)
    data ={
        'obj' : id_,
        'model': Movement.objects.filter(code=id_.id).order_by("-id")
    }
    data['admin'] = Admin(request)
    data['inventory'] = 'active'
    data['title'] = 'Inventario'
    return render(request, 'inventory/movement_detail.html', data)

templates/inventory/create_value.html
{% extends 'base/base.html' %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="container-fluid">
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-10">
            <input type="text" name="title" id="id_title" required class="form-control" placeholder="Ingrese nombre del {{ title }}"/>
        </div>
        <div class="col-lg-2">
            <button class="btn btn-primary btn-round" type='submit'>Agregar</button>
        </div>
    </div>
</form>
{% if data %}
    {% for datas in data %}
    {{ datas.title }} <br>
    {% endfor %}
{% endif %}
</div>


{% endblock content %}
{% block js %}

{% endblock js %}

templates/inventory/index.html
{% extends 'base/base.html' %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row">
            <div class="col-lg-12 col-md-12" align="center">
                <h3>Inventario actual</h3>
            </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
             <div class="card">
                <div class="card-header" data-background-color="green">
                    <div class="row " align="center" style="font-size: x-large;">
                        <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Codigo</div></a>
                        <a href=""> <div class="col-md-4 col-sm-2 fix-tabla">Descripcion</div></a>
                        <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Grupo</div></a>
                        <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Cantidad</div></a>
                        <div class="col-md-2 col-sm-2">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="material-icons" style="font-size: xx-large" >add_circle</i>
                            <div class="ripple-container"></div></a>
                            <ul class="dropdown-menu" data-background-color="green">
                                <li><a href="{% url 'inventory:maintainer_item' 'create' '0' %}">Añadir item</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                 <div class="card-content">
                 </div>
                  {% if data %}
                      {% for datas in data %}
                            <div class="row card-footer hidden-md" align="center">
                                <a href="{% url 'inventory:movement_detail' datas.code %}">
                                    <div class="col-md-2 col-sm-2 " align="right" style="padding-left: 6%; padding-right: 20px">{{ datas.code }}</div>
                                    <div class="col-md-4 col-sm-2 " align="left">{{ datas.description }}</div>
                                    <div class="col-md-2 col-sm-2 " >{{ datas.group }}</div>
                                    <div class="col-md-2 col-sm-2 " >{{ datas.sum }}</div>
                                </a>
                                <div class="col-md-2 col-sm-2">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            <i class="material-icons" style="color: #43a047">arrow_drop_down_circle</i>
                                    <div class="ripple-container"></div></a>
                                    <ul class="dropdown-menu" data-background-color="green">
                                        <li><a href="{% url 'inventory:movement' 'create' datas.code %}">Añadir</a></li>
                                        <li><a href="{% url 'inventory:maintainer_item' 'edit' datas.code %}">Editar</a></li>
                                        <li><a href="{% url 'inventory:movement_detail' datas.code %}">Movimientos</a></li>
                                    </ul>
                                </div>
                            </div>
                         {% endfor %}
                     {% else %}
                         Sin datos
                     {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}
{% block js %}

{% endblock js %}

templates/inventory/maintainer_item.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container-fluid">
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-2">
            <input type="text" name="code" value="{{ edit.code }}" required class="form-control" placeholder="Codigo"/>
        </div>
        <div class="col-lg-6">
            <input type="text" name="description" value="{{ edit.description }}" required class=" form-control" maxlength="50" placeholder="Descripcion" />
        </div>
        <div class="col-lg-2">
            <select name="group" class="form-control" >
            {% if edit %}
                <option value="{{ edit.group_id }}" >{{ edit.group }}</option>
            {% else %}
                <option value="0">Grupo</option>
            {% endif %}
                {% for groups in group %}
                    <option value="{{ groups.id }}">{{ groups }}</option>
                {% endfor %}

            </select>
            <div align="right">
                <a href="{% url 'inventory:create_value' 'group' %}" >Añadir</a>
            </div>
        </div>
        <div class="col-lg-2" >
            <button class="btn btn-primary btn-round btn-green" type='submit'>Agregar</button>
        </div>
    </div>
</form>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
             <div class="card">
                <div class="card-header hidden-xs" data-background-color="green">
                    <div class="row " align="center" style="font-size: x-large;">
                        <a href=""><div class="col-md-2 col-sm-2" >Codigo</div></a>
                        <a href=""> <div class="col-md-6 col-sm-2">Descripcion</div></a>
                        <a href=""><div class="col-md-2 col-sm-2">Grupo</div></a>
                    </div>
                </div>
                 <div class="card-content">
                 </div>
                  {% if data %}
                      {% for datas in data %}
                            <div class="row card-footer hidden-md" align="center">
                                <div class="col-md-2 col-sm-2 " align="left" style="padding-left: 6%">{{ datas.code }}</div>
                                <div class="col-md-6 col-sm-2 " align="left">{{ datas.description }}</div>
                                <div class="col-md-2 col-sm-2 " >{{ datas.group }}</div>
                                <div class="col-md-2 col-sm-2">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <i class="material-icons">keyboard_arrow_down</i> Acciones
                                    <div class="ripple-container"></div></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'inventory:movement' 'create' datas.code %}">Añadir</a></li>
                                        <li><a href="{% url 'inventory:maintainer_item' 'edit' datas.code %}">Editar</a></li>
                                        <li><a href="{% url 'inventory:movement_detail' datas.code %}">Movimientos</a></li>
                                    </ul>
                                </div>
                            </div>
                         {% endfor %}
                     {% else %}
                         Sin datos
                     {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}
{% block js %}

{% endblock js %}

templates/inventory/movement.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container-fluid">
    <form method="post" >
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-4">
            {% if select %}
                <input class="form-control" value="{{ select }} {{ select.description }} " disabled >
                <select name="code" id="id_code" style="visibility:hidden">
                    <option value="{{ select.id }}"></option>
                </select>
            {% else %}
                <select name="code" class="form-control" id="id_code">
                    <option value="0">Item</option>
                    {% for items in item %}
                        <option value="{{ items.id }}">{{ items }} {{ items.description }}</option>
                    {% endfor %}

                </select>
            {% endif %}
            </div>
            <div class="col-lg-2">
                <select name="state" class="form-control" id="id_state">
                    <option value="0">Estado</option>
                    {% for states in state %}
                        <option value="{{ states.id }}">{{ states }}</option>
                    {% endfor %}
                </select>
                <div align="right">
                    <a href="{% url 'inventory:create_value' 'state' %}" >Añadir</a>
                </div>
            </div>
            <div class="col-lg-2">
                <select name="location" class="form-control" id="id_location">
                    <option value="0">Ubicacion</option>
                    {% for locations in location %}
                        <option value="{{ locations.id }}">{{ locations }}</option>
                    {% endfor %}

                </select>
                <div align="right">
                    <a href="{% url 'inventory:create_value' 'location' %}" >Añadir</a>
                </div>
            </div>
            <div class="col-lg-2">
                <input type="text" name="stock" required class="form-control"  id="id_stock" placeholder="Cantidad"/>
            </div>
            <div class="col-lg-2">
                <button class="btn btn-primary btn-round" type='submit'>Agregar</button>
            </div>
        </div>
    </form>
<div class="row">
    <div class="col-lg-12" align="center">
        <h3>Ultimos 5 movimientos</h3>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
             <div class="card">
                <div class="card-header hidden-xs" data-background-color="green">
                    <div class="row " align="center" style="font-size: x-large;">
                        <a href=""><div class="col-md-3 col-sm-2">Fecha y hora</div></a>
                        <a href=""><div class="col-md-3 col-sm-2">Ubicacion</div></a>
                        <a href=""><div class="col-md-3 col-sm-2">Estado</div></a>
                        <a href=""><div class="col-md-3 col-sm-2">Cantidad</div></a>
                    </div>
                </div>
                 <div class="card-content">
                 </div>
                  {% if data %}
                    {% for datas in data %}
                        {% if datas.stock < 0 %}
                        <div class="row card-footer hidden-md" align="center" style="color: darkred">
                            <div class="col-md-3 col-sm-2 ">{{ datas.created_at }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.location }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.state }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.stock }}</div>
                        </div>
                        {% else %}
                        <div class="row card-footer hidden-md" align="center">
                            <div class="col-md-3 col-sm-2 ">{{ datas.created_at }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.location }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.state }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.stock }}</div>
                        </div>
                        {% endif %}
                    {% endfor %}
                    <div class="row">
                      <div class="col-lg-12" align="right">
                          <a href="{% url 'inventory:movement_detail' code %}"><h5>Mas movimientos</h5></a>
                      </div>
                    </div>
                  {% else %}
                    <div class="row">
                    <div class="col-lg-12" align="center">
                    <h3> Sin movimientos </h3>
                    </div>
                    </div>
                  {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}
{% block js %}

{% endblock js %}

templates/inventory/movement_detail.html
{% extends 'base/base.html' %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2" align="center">
            <h5>Item : </h5>
        </div>
        <div class="col-lg-10" align="left">
            <h5>{{ obj.code }} - {{ obj.description }} - {{ obj.group }}</h5>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
             <div class="card">
                <div class="card-header hidden-xs" data-background-color="green">
                    <div class="row " align="center" style="font-size: x-large;">
                        <a href=""><div class="col-md-3 col-sm-2">Fecha y hora</div></a>
                        <a href=""><div class="col-md-3 col-sm-2">Ubicacion</div></a>
                        <a href=""><div class="col-md-3 col-sm-2">Estado</div></a>
                        <a href=""><div class="col-md-3 col-sm-2">Cantidad</div></a>
                    </div>
                </div>
                 <div class="card-content">
                 </div>
                  {% if model %}
                    {% for datas in model %}
                        {% if datas.stock < 0 %}
                        <div class="row card-footer hidden-md" align="center" style="color: darkred">
                            <div class="col-md-3 col-sm-2 ">{{ datas.created_at }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.location }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.state }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.stock }}</div>
                        </div>
                        {% else %}
                        <div class="row card-footer hidden-md" align="center">
                            <div class="col-md-3 col-sm-2 ">{{ datas.created_at }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.location }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.state }}</div>
                            <div class="col-md-3 col-sm-2 " >{{ datas.stock }}</div>
                        </div>
                        {% endif %}
                    {% endfor %}
                  {% else %}
                    <div class="row">
                    <div class="col-lg-12" align="center">
                    <h3> Sin movimientos </h3>
                    </div>
                    </div>
                  {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block js %}

{% endblock js %}