apps/home/urls.py
from django.conf.urls import url, include
from apps.home.views import index, Verify
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    url(r'^zohoverify/verifyforzoho.html$', Verify, name="verifyforzoho"),
]

apps/screen/urls.py
from django.conf.urls import url, include
from apps.screen.views import index, Settings, Prevent_, Video_
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^settings/$', login_required(Settings), name="settings"),
    url(r'^prevent/(?P<funct>\w+)/(?P<type>\d+)/(?P<id>\d+)$', login_required(Prevent_), name="prevent"),
    url(r'^video/(?P<funct>\w+)/(?P<type>\d+)$', login_required(Video_), name="video"),
]

apps/user/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.user.views import Editaccount,Registeruser, Listuser, Edit_type,Deactivate, Activate

urlpatterns = [
 #   url(r'^$', index, name='ticket'),
    url(r'^register', login_required(Registeruser), name='register'),
    url(r'^list$', login_required(Listuser), name='list'),
    url(r'^deactivate/(?P<id>\d+)/$', login_required(Deactivate), name='deactivate'),
    url(r'^activate/(?P<id>\d+)/$', login_required(Activate), name='activate'),
    url(r'^edit/(?P<id>\d+)$', login_required(Editaccount), name='edit'),
    url(r'^type/(?P<id>\d+)/(?P<type>\w+)/$', login_required(Edit_type), name='edit_type'),
]

prevex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='index')),
    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^screen/', include('apps.screen.urls', namespace='screen')),
    url(r'^inventory/', include('apps.inventory.urls', namespace='inventory')),
    url(r'^binnacle/', include('apps.binnacle.urls', namespace='binnacle')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]
urlpatterns += [
    url(r'^accounts/login/', login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="es">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}" />
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    {% block meta %}

    {% endblock meta %}


    <title>PREVEX - {{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/material-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body >

        {% if screencast %}
            {% block screen %}

            {% endblock screen %}
        {% else %}
	<div class="wrapper">
	    <div class="sidebar" data-color="purple" data-image="{% static 'img/sidebar-1.jpg' %}">
			<div class="logo">
				<a href="" class="simple-text">
					PREVEX
				</a>
			</div>

	    	<div class="sidebar-wrapper">
                {% block sidebar %}
                        {% include 'base/sidebar.html' %}

                {% endblock sidebar %}
	    	</div>
	    </div>

	    <div class="main-panel">
			<nav class="navbar navbar-transparent navbar-absolute">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#">{% block option %}{{ option }}{% endblock option %}</a>

					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <i class="material-icons">ondemand_video</i>
                                <div class="ripple-container"></div></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{% url 'screen:index' %}">
                                            <i class="material-icons">ondemand_video</i> Ver
                                        </a>
                                        <a href="{% url 'screen:settings' %}">
                                            <i class="material-icons">settings </i> Ajustes
                                        </a>
                                    </li>

                                </ul>
                            </li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	 							   <i class="material-icons">person</i> {{ user.get_username }}
	 							   <p class="hidden-lg hidden-md">Profile</p>
								</a>
								<ul class="dropdown-menu">
									<li><a href="{% url 'user:edit' '0' %}">Config. cuenta</a></li>
									<li><a href="{% url 'logout' %}">Salir</a></li>
								</ul>
							</li>
						</ul>
                <!--
						<form class="navbar-form navbar-right" role="search">
							<div class="form-group  is-empty">
								<input type="text" class="form-control" placeholder="Search">
								<span class="material-input"></span>
							</div>
							<button type="submit" class="btn btn-white btn-round btn-just-icon">
								<i class="material-icons">search</i><div class="ripple-container"></div>
							</button>
						</form> -->
					</div>
				</div>
			</nav>

			<div class="content">
            {% block content %}

            {% endblock content %}
			</div>

			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-right">
                        Desarrollado por <a href="mailto:octavio@vicius.cl">Octavio Cubillos</a> - powered by
                        <a href="https://vicius2.herokuapp.com/"  target="_blank">
                            <img src="https://vicius2.herokuapp.com/static/img/vicius-black.png" alt="" title="" height="20">
                        </a> -
                        <i class="material-icons" style="font-size: small">copyright</i> Derechos reservados -
                        <a href="http://demos.creative-tim.com/material-dashboard/examples/dashboard.html"  target="_blank">
                             Material By CREATIVE TIM
                        </a>
                    </nav>
				</div>
			</footer>
		</div>
	</div>
{% endif %}
</body>

<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/chartist.min.js' %}"></script>
<script src="{% static 'js/material.min.js' %}"></script>
<script src="{% static 'js/bootstrap-notify.js' %}"></script>
<script src="{% static 'js/material-dashboard.js' %}"></script>
<script src="{% static 'js/style.js' %}"></script>
<script src="{% static 'js/material-dashboard.js' %}"></script>
<script src="{% static 'js/style.js' %}"></script>
<script src="{% static 'js/material-dashboard.js' %}"></script>
{% block js %}

{% endblock js %}


</html>

templates/base/sidebar.html
 <ul class="nav">
    <li class="{{ home }}">
        <a href="{% url 'home:index' %}">
            <i class="material-icons">home</i>
            <p>Inicio</p>
        </a>
    </li>
    <li class="{{ inventory }}">
        <a href="{% url 'inventory:index' %}">
            <i class="material-icons">format_list_numbered</i>
            <p>Inventario</p>
        </a>
    </li>
    <li class="{{ binnacle }}">
        <a href="{% url 'binnacle:index' %}">
            <i class="material-icons">import_contacts</i>
            <p>Bitacora</p>
        </a>
    </li>
    <li class="{{ screen }}">
        <a href="{% url 'screen:settings' %}">
            <i class="material-icons">desktop_windows</i>
            <p>Pantalla</p>
        </a>
    </li>
     {% if admin %}
    <li class="{{ adminuser }}">
        <a href="{% url 'user:list' %}">
            <i class="material-icons">group</i>
            <p>Admin. de usuarios</p>
        </a>
    </li>
     {% endif  %}
</ul>