apps/binnacle/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.binnacle.views import index, Create_value, Create_working, Create_accident, All_accident, All_repose

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accident/(?P<funct>\w+)/(?P<value>\d+)$', login_required(Create_accident), name="accident"),
    url(r'^(?P<value>\w+)/(?P<funct>\w+)/(?P<id>\d+)$', login_required(Create_value), name="create_value"),
    url(r'^working/(?P<value>\d+)$', login_required(Create_working), name="working"),
    url(r'^all_accident/$', login_required(All_accident), name="all_accident"),
    url(r'^all_repose/$', login_required(All_repose), name="all_repose"),
    ]

prevex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='index')),
    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^screen/', include('apps.screen.urls', namespace='screen')),
    url(r'^inventory/', include('apps.inventory.urls', namespace='inventory')),
    url(r'^binnacle/', include('apps.binnacle.urls', namespace='binnacle')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]
urlpatterns += [
    url(r'^accounts/login/', login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/binnacle/models.py
from django.db import models

# Create your models here.

class Area(models.Model):
    title = models.CharField(null=False, max_length=50)
    detail = models.CharField(null=False, max_length=200)
    def __str__(self):
        return '{}'.format(self.title)

class Workstation(models.Model):
    title = models.CharField(null=False, max_length=50)
    detail = models.CharField(null=False, max_length=200)
    def __str__(self):
        return '{}'.format(self.title)

class Working(models.Model):
    name = models.CharField(null=False, max_length=50)
    workstation = models.ForeignKey(Workstation, null=False, blank=True, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, null=False, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.name+' - '+self.workstation.title+' - '+self.area.title)

class Type_Accident(models.Model):
    title = models.CharField(null=False, max_length=50)
    detail = models.CharField(null=False, max_length=200)
    def __str__(self):
        return '{}'.format(self.title)

class Accident(models.Model):
    working = models.ForeignKey(Working, null=False, blank=True, on_delete=models.CASCADE)
    year  = models.IntegerField(null=False)
    date = models.DateField(null=False)
    hour = models.TimeField(null=False)
    type = models.ForeignKey(Type_Accident, null=False, blank=True, on_delete=models.CASCADE)
    description = models.TextField(null=False)
    observation = models.CharField(max_length=100)
    area = models.ForeignKey(Area, null=False, blank=True, on_delete=models.CASCADE)
    workstation = models.ForeignKey(Workstation, null=False, blank=True, on_delete=models.CASCADE)
    repose = models.IntegerField()

apps/binnacle/forms.py
from django import forms
from apps.binnacle.models import Working, Workstation, Accident, Area, Type_Accident

class WorkstationForm(forms.ModelForm):

    class Meta:
        model = Workstation
        fields = [
            'title',
            'detail'
        ]
        labels = {
            'title':'Title',
            'detail':'Detail'
        }
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'detail' : forms.TextInput(attrs={'class':'form-control'})
        }

class AreaForm(forms.ModelForm):

    class Meta:
        model = Area
        fields = [
            'title',
            'detail'
        ]
        labels = {
            'title':'Title',
            'detail':'Detail'
        }
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'detail' : forms.TextInput(attrs={'class':'form-control'})
        }

class Type_AccidentForm(forms.ModelForm):

    class Meta:
        model = Type_Accident
        fields = [
            'title',
            'detail'
        ]
        labels = {
            'title':'Title',
            'detail':'Detail'
        }
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'detail' : forms.TextInput(attrs={'class':'form-control'})
        }

class WorkingForm(forms.ModelForm):

    class Meta:
        model = Working
        fields = [
            'name',
            'workstation',
            'area'
        ]
        labels = {
            'name': 'Name',
            'workstation': 'Workstation',
            'area': 'Area'
        }
        widgets = {
            'name' :forms.TextInput(attrs={'class':'form-control'}),
            'workstation' :forms.Select(attrs={'class':'form-control'}),
            'area' :forms.Select(attrs={'class':'form-control'})
        }


class AccidentForm(forms.ModelForm):

    class Meta:
        model = Accident
        fields = [
            'working',
            'year',
            'date',
            'hour',
            'type',
            'description',
            'observation',
            'area',
            'workstation',
            'repose'
        ]
        labels = {
            'working': 'Working',
            'year': 'Year',
            'date': 'Date',
            'hour': 'Hour',
            'type': 'Type',
            'description': 'Description',
            'observation': 'Observation',
            'area': 'Area',
            'workstation': 'Workstation',
            'repose':'Repose'
        }
        widgets = {
            'working' :forms.Select(attrs={'class':'form-control'}),
            'year' :forms.TextInput(attrs={'class':'form-control'}),
            'date' :forms.TextInput(attrs={'class':'form-control'}),
            'hour' :forms.TextInput(attrs={'class':'form-control'}),
            'type' :forms.Select(attrs={'class':'form-control'}),
            'description' :forms.Textarea(attrs={'class':'form-control'}),
            'observation' :forms.TextInput(attrs={'class':'form-control'}),
            'area' :forms.Select(attrs={'class':'form-control'}),
            'workstation' :forms.Select(attrs={'class':'form-control'}),
            'repose' :forms.TextInput(attrs={'class':'form-control'}),
        }

apps/binnacle/views.py
from django.shortcuts import render, redirect
from apps.binnacle.models import Area, Accident, Workstation, Working, Type_Accident
from apps.binnacle.forms import WorkingForm, WorkstationForm,  AreaForm, AccidentForm, Type_AccidentForm
from django.db.models import Count
from apps.user.views import Admin
from django.contrib.auth.models import User

import os

# Create your views here.

def index(request):
    data = {}
    data['admin'] = Admin(request)
    data['binnacle'] = 'active'
    data['model'] = Accident.objects.all().order_by('-id')[:5]
    data['accidentados'] = Accident.objects.all().aggregate(Count('id'))
    data['accidentados'] = data['accidentados']['id__count']
    repose = 0
    for item in Accident.objects.all():
        if item.repose != 0:
            repose =repose +1
    data['repose']=repose
    return render(request, 'binnacle/index.html', data)

def All_accident(request):
    data = {}
    data['admin'] = Admin(request)
    data['binnacle'] = 'active'
    data['model'] = Accident.objects.all().order_by('-id')
    return render(request, 'binnacle/all_accident.html', data)

def All_repose(request):
    data = {}
    data['admin'] = Admin(request)
    data['binnacle'] = 'active'
    data['model']={}
    llo = Accident.objects.filter().order_by('-id')
    for llos in llo:
        if llos.repose != 0:
            data['model'][llos]=llos

    return render(request, 'binnacle/all_accident.html', data)

def Create_value(request, value, funct, id):
    data = { 'binnacle': 'active'}
    data['admin'] = Admin(request)
    data['value'] = value
    id_int = int(id)
    form = {}
    if value == 'workstation':
        data['model'] = Workstation.objects.all().order_by('title')
        data['title'] = 'puesto de trabajo'
        if funct == 'create':
            form = WorkstationForm(request.POST)
            if request.method == 'POST':
                if form.is_valid():
                    form.save()
        elif funct == 'edit':
            data['edit'] = Workstation.objects.get(id=id_int)
            if request.method == "GET":
                data['form'] = WorkstationForm(instance=data['edit'])
                print(data['form'])
            else:
                form = WorkstationForm(request.POST, instance=data['edit'])
                if form.is_valid():
                    form.save()
                return redirect('binnacle:create_value', value, 'create', '0')
    elif value == 'area':
        data['model'] = Area.objects.all().order_by('title')
        data['title'] = 'area de trabajo'
        if funct == 'create':
            form = AreaForm(request.POST)
            if request.method == 'POST':
                if form.is_valid():
                    form.save()
        elif funct == 'edit':
            data['edit'] = Area.objects.get(id=id_int)
            if request.method == "GET":
                data['form'] = AreaForm(instance=data['edit'])
                print(data['form'])
            else:
                form = AreaForm(request.POST, instance=data['edit'])
                if form.is_valid():
                    form.save()
                return redirect('binnacle:create_value', value, 'create', '0')
    elif value == 'type':
        data['model'] = Type_Accident.objects.all().order_by('title')
        data['title'] = 'tipo de accidente'
        if funct == 'create':
            form = Type_AccidentForm(request.POST)
            if request.method == 'POST':
                if form.is_valid():
                    form.save()
        elif funct == 'edit':
            data['edit'] = Type_Accident.objects.get(id=id_int)
            if request.method == "GET":
                form = Type_AccidentForm(instance=data['edit'])

            else:
                form = Type_AccidentForm(request.POST, instance=data['edit'])
                if form.is_valid():
                    form.save()
                return redirect('binnacle:create_value', value, 'create', '0')
    return render(request, 'binnacle/create_value.html', data)

def Create_working(request, value):
    data = {'binnacle': 'active'}
    data['admin'] = Admin(request)
    data['model'] = Working.objects.all().order_by('name')
    value_int = int(value)
    if value_int == 0:
        data['area'] = Area.objects.all().order_by('title')
        data['workstation'] = Workstation.objects.all().order_by('title')
        data['form'] = WorkingForm()
        data['title'] = 'trabajador'
        if request.method == 'POST':
            form = WorkingForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('binnacle:working', value)
    return render(request, 'binnacle/working.html', data)

def Create_accident(request,funct, value):
    data = {'binnacle': 'active'}
    data['admin'] = Admin(request)
    data['model'] = Accident.objects.all()
    value_int = int(value)
    data['area'] = Area.objects.all().order_by('title')
    data['type'] = Type_Accident.objects.all().order_by('title')
    data['workstation'] = Workstation.objects.all().order_by('title')
    data['working'] = Working.objects.all().order_by('name')
    data['form'] = AccidentForm()
    data['title'] = 'accidente'
    if funct == 'create':
        if request.method == 'POST':
            form = AccidentForm(request.POST)
            if form.is_valid():
                form.save()
                Send(str(Accident.objects.last().id))
                return redirect('binnacle:index')
            else:
                print(form.is_valid())
                print(form.errors)
    elif funct == 'edit':
        data['edit']=Accident.objects.get(id=value_int)
        if request.method == 'POST':
            form = AccidentForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('binnacle:index')
            else:
                print(form.is_valid())
                print(form.errors)
    elif funct == 'view':
        data['edit']=Accident.objects.get(id=value_int)
        data['view'] = 'disabled'
        if request.method == 'POST':
            form = AccidentForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('binnacle:index')
            else:
                print(form.is_valid())
                print(form.errors)
    return render(request, 'binnacle/accident.html', data)


from django.core.mail import send_mail

def Notify(subject, message,receiver):
    send_mail(subject,
               message,
              "support@prevex.herokuapp.com",
              [receiver],
                fail_silently = False)
def Send(id):
    print('id del guardado es'+id)
    dominio = 'http://0.0.0.0:8888/'
    if os.getenv('SETTINGS_MODE') in ['PROD']:
        dominio = 'https://prevex.herokuapp.com/'
    email = User.objects.all().order_by('id')
    for llo in email:
        print(llo)
        Notify('Se a registrado un nuevo accidente',
               'Se a ingresado un nuevo accidente, haga clic en el siguiente enlace para ver detalles. '+dominio+'binnacle/accident/view/'+id,
               llo.email)

templates/binnacle/accident.html
{% extends 'base/base.html' %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="container-fluid">
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-12" align="center">
            <h3>Datos del trabajador accidentado</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            <select name="working" {{ view }} id="id_working" class="form-control">
            {% if edit %}
                <option value="{{ edit.working.id }}">{{ edit.working }}</option>
            {% endif %}
                {% for items in working %}
                    <option value="{{ items.id }}">{{ items }}</option>
                {% endfor %}
            </select>
                <div align="right">
                    <a href="{% url 'binnacle:working' '0'%}" >Añadir trabajador</a>
                </div>

        </div>

        <div class="col-lg-4"style="margin-left: 0px">
            <div class="row" style="margin-left: 0px">
                <div class="col-xs-5" style="margin-left: 0px">
                    {% if edad %}
                        <input type="number" {{ view }} name="year" id="id_year" class="form-control" value="{{ edit.year }}" required />
                    {% else %}
                        <input type="number" {{ view }} name="year" id="id_year" class="form-control" value="18" required />
                    {% endif %}
                 </div>
                 <div class="col-xs-3" style="margin-left: 0px">
                        <input type="text" {{ view }} class="form-control" value="años" disabled/>
                </div>
            </div>
        </div>
        <div class="col-lg-4" style="margin-left: 0px">
            <div class="row" style="margin-left: 0px">
                 <div class="col-xs-3" style="margin-left: 0px">
                        <input type="text" {{ view }} class="form-control" value="Reposo" disabled/>
                </div>
                <div class="col-xs-4" style="margin-left: 0px">
                    {% if edit %}
                        <input type="number" {{ view }} name="repose" id="id_repose" class="form-control" value="{{ edit.repose }}" required />
                    {% else %}
                        <input type="number" {{ view }} name="repose" id="id_repose" class="form-control" value="0" required />
                    {% endif %}
                 </div>
                 <div class="col-xs-3" style="margin-left: 0px">
                        <input type="text" {{ view }} class="form-control" value="dia(s)" disabled/>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12" align="center">
            <h3>Datos del Accidente</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <select name="type" {{ view }} id="id_type" class="form-control">
            {% if edit %}
                <option value="{{ edit.type.id }}">{{ edit.type }}</option>
            {% endif %}
                {% for items in type %}
                    <option value="{{ items.id }}">{{ items }}</option>
                {% endfor %}
            </select>
                <div align="right">
                    <a href="{% url 'binnacle:create_value' 'type' 'create' '0' %}" >Añadir tipo de  accidente</a>
                </div>
        </div>
        <div class="col-lg-2">
            {% if edit %}
            <input type="text" {{ view }} name="date" value="{{ edit.date.day }}/{{ edit.date.month }}/{{ edit.date.year }}" id="id_date" class="form-control" required />
            {% else %}
            <input type="date" {{ view }} name="date" id="id_date" class="form-control" required />
            {% endif %}
        </div>
        <div class="col-lg-2">
            <input type="time" {{ view }} name="hour" value="{{ edit.hour }}" id="id_hour" class="form-control" required />
        </div>
        <div class="col-lg-2">
            <select name="workstation" {{ view }} id="id_workstation" class="form-control">
                {% if edit %}
                    <option value="{{ edit.workstation.id }}">{{ edit.workstation }}</option>
                {% endif %}
                {% for items in workstation %}
                    <option value="{{ items.id }}">{{ items }}</option>
                {% endfor %}
            </select>
                <div align="right">
                    <a href="{% url 'binnacle:create_value' 'workstation' 'create' '0' %}" >Añadir puesto</a>
                </div>

        </div>
        <div class="col-lg-2">
            <select name="area" {{ view }} id="id_area" class="form-control">
                {% if edit %}
                    <option value="{{ edit.area.id }}">{{ edit.area }}</option>
                {% endif %}
                {% for items in area %}
                    <option value="{{ items.id }}">{{ items }}</option>
                {% endfor %}
            </select>
                <div align="right">
                    <a href="{% url 'binnacle:create_value' 'area' 'create' '0' %}" >Añadir area</a>
                </div>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <textarea name="description" {{ view }} required rows="3" id="id_description" class="form-control" placeholder="Detalles del accidente.">{{ edit.description }}</textarea>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-8">
            {% if edit %}
                <input type="text" {{ view }} name="observation" value="{{ edit.observation }}" required id="id_observation" class="form-control" placeholder="Observacion"/>
            {% else %}
                <input type="text" {{ view }} name="observation" value="Sin Observaciones" required id="id_observation" class="form-control" placeholder="Observacion"/>
            {% endif %}
        </div>
        {% if view %}
            <div class="col-lg-4" align="center">
                <a href="javascript:history.back(-1);" class="btn btn-primary btn-round" type='reset'>Volver</a>
            </div>
        {% else %}
        <div class="col-lg-2">
            <button class="btn btn-primary btn-round" type='reset'>Limpiar</button>
        </div>
        <div class="col-lg-2">
            <button class="btn btn-primary btn-round" type='submit'>Agregar</button>
        </div>
        {% endif %}
    </div>

</form>

  <!--  <div class="row">
            <div class="col-lg-12 col-md-12">
                 <div class="card">
                    <div class="card-header hidden-xs" data-background-color="red">
                        <div class="row " align="center" style="font-size: x-large;">
                            <a href=""> <div class="col-md-2 col-sm-2 fix-tabla" align="center">#</div></a>
                            <a href=""> <div class="col-md-4 col-sm-2 fix-tabla">Nombre</div></a>
                            <a href=""> <div class="col-md-2 col-sm-2 fix-tabla">Puesto de trabajo</div></a>
                            <a href=""> <div class="col-md-2 col-sm-2 fix-tabla">Area</div></a>
                            <a href=""><div class="col-md-2 col-sm-2"></div>
                            </a>
                        </div>
                    </div>
                     <div class="card-content">
                     </div>
                      {% if model %}
                          {% for datas in model %}
                                <div class="row card-footer hidden-md" align="center">
                                    <div class="col-md-2 col-sm-2 " align="center" style="padding-left: 6%; padding-right: 20px">{{ datas.working }}</div>
                                    <div class="col-md-2 col-sm-2 " align="center" style="padding-left: 6%; padding-right: 20px">{{ datas.date }}-{{ datas.hour }}</div>
                                    <div class="col-md-2 col-sm-2 " align="center" style="padding-left: 6%; padding-right: 20px">{{ datas.type }}</div>
                                    <div class="col-md-4 col-sm-2 " align="center" style="padding-left: 6%; padding-right: 20px">{{ datas.description }}</div>
                                    <div class="col-md-2 col-sm-2">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            <i class="material-icons">keyboard_arrow_down</i> Acciones
                                        <div class="ripple-container"></div></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="">Editar</a></li>
                                        </ul>
                                    </div>
                                </div>
                             {% endfor %}
                         {% else %}
                          <div class="row">
                              <div class="col-lg-12" align="center">
                                  <h3>Sin datos</h3>
                              </div>
                          </div>
                         {% endif %}
                </div>
            </div>
        </div>
</div> -->
{% endblock content %}

templates/binnacle/index.html
{% extends 'base/base.html' %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4">
            <div class="card card-stats">
                <div class="card-header" data-background-color="red">
                    <i class="material-icons">mood_bad</i>
                </div>
                <div class="card-content">
                    <h4 class="title"> <small> Actualmente hay </small> </h4>
                    <h3 class="title">{{ accidentados }}<small> accidentes regist.</small></h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons ">list</i> <a href="{% url 'binnacle:all_accident' %}" style="color: #727272"> Ver todos los registros.</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card card-stats">
                <div class="card-header" data-background-color="red">
                    <i class="material-icons">hotel</i>
                </div>
                <div class="card-content">
                    <h4 class="title"> <small> Trabajadores hay </small> </h4>
                    <h3 class="title">{{ repose }}<small> en descanso </small></h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons ">list</i> <a href="{% url 'binnacle:all_repose' %}" style="color: #727272"> Ver todos los registros.</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card card-stats">
                <div class="card-header" data-background-color="red">
                    <i class="material-icons">view_comfy</i>
                </div>
                <div class="card-content" style="padding-bottom: 26px">
                    <h2 class="title"> <small> Ver otros listado </small> </h2>
                </div>
                <div class="card-footer">
                    <a href="#" class="status" data-toggle="dropdown" aria-expanded="false">
                        <div class="stats" style="font-size: large">
                            <i class="material-icons" style="padding-bottom: 10px">arrow_drop_down_circle</i> Mas opciones
                            <div class="ripple-container"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu" data-background-color="red">
                        <li><a href="{% url 'binnacle:working' '0' %}">Listado de trabajadores</a></li>
                        <li><a href="{%  url 'binnacle:create_value' 'area' 'create' '0' %}">Listado de areas</a></li>
                        <li><a href="{%  url 'binnacle:create_value' 'workstation' 'create' '0' %}">Listado de puestos de trabajo</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-lg-12 col-md-12" align="center">
                <h3>Ultimos 5 registros</h3>
            </div>
    </div>

    <div class="row">
            <div class="col-lg-12 col-md-12">
                 <div class="card">
                    <div class="card-header" data-background-color="red">
                        <div class="row " align="center" style="font-size: x-large;">
                            <a href=""> <div class="col-md-3 col-sm-2 fix-tabla">Fecha</div></a>
                            <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Trabajador</div></a>
                            <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Tipo accid.</div></a>
                            <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Area</div></a>
                            <a href=""><div class="col-md-2 col-sm-2 fix-tabla">Puesto</div></a>
                            <a href="{% url 'binnacle:accident' 'create' '0' %}">
                                <div class="col-md-1 col-sm-1">
                                    <i class="material-icons" style="font-size: xx-large" >add_circle</i>
                                </div>
                            </a>
                        </div>
                    </div>
                     <div class="card-content">
                     </div>
                      {% if model %}
                          {% for datas in model %}
                                <div class="row card-footer hidden-md" align="center">
                                    <a href="{% url 'binnacle:accident' 'view' datas.id %}"><div class="col-md-3 col-sm-2 " align="center" style="">{{ datas.date }} - {{ datas.hour }}</div>
                                    <div class="col-md-2 col-sm-2 " align="center">{{ datas.working.name }}</div>
                                    <div class="col-md-2 col-sm-2 " >{{ datas.type }}</div>
                                    <div class="col-md-2 col-sm-2 " >{{ datas.area }}</div>
                                    <div class="col-md-2 col-sm-2 " >{{ datas.workstation}}</div></a>
                                    <div class="col-md-1 col-sm-1">
                                        <a href="{% url 'binnacle:accident' 'edit' datas.id %}" rel="tooltip" data-original-title="Editar" title=""><i class="material-icons">mode_edit</i></a>

                                    </div>
                                </div>
                             {% endfor %}
                         {% else %}
                          <div class="row">
                              <div class="col-lg-12" align="center">
                                  <h3>Sin datos</h3>
                              </div>
                          </div>
                         {% endif %}
                </div>
            </div>
        </div>
</div>


{% endblock content %}
{% block js %}

{% endblock js %}