apps/binnacle/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.binnacle.views import index, Create_value, Create_working, Create_accident, All_accident, All_repose

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accident/(?P<funct>\w+)/(?P<value>\d+)$', login_required(Create_accident), name="accident"),
    url(r'^(?P<value>\w+)/(?P<funct>\w+)/(?P<id>\d+)$', login_required(Create_value), name="create_value"),
    url(r'^working/(?P<value>\d+)$', login_required(Create_working), name="working"),
    url(r'^all_accident/$', login_required(All_accident), name="all_accident"),
    url(r'^all_repose/$', login_required(All_repose), name="all_repose"),
    ]

apps/screen/urls.py
from django.conf.urls import url, include
from apps.screen.views import index, Settings, Prevent_, Video_
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^settings/$', login_required(Settings), name="settings"),
    url(r'^prevent/(?P<funct>\w+)/(?P<type>\d+)/(?P<id>\d+)$', login_required(Prevent_), name="prevent"),
    url(r'^video/(?P<funct>\w+)/(?P<type>\d+)$', login_required(Video_), name="video"),
]

prevex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='index')),
    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^screen/', include('apps.screen.urls', namespace='screen')),
    url(r'^inventory/', include('apps.inventory.urls', namespace='inventory')),
    url(r'^binnacle/', include('apps.binnacle.urls', namespace='binnacle')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]
urlpatterns += [
    url(r'^accounts/login/', login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/screen/models.py
from django.db import models
from apps.binnacle.models import Type_Accident

# Create your models here.
class Prevent(models.Model):
    type = models.ForeignKey(Type_Accident, null=False, blank=True, on_delete=models.CASCADE)
    item = models.CharField(max_length=300)
    def __str__(self):
        return '{}'.format(self.type)

class Video(models.Model):
    type = models.ForeignKey(Type_Accident, null=False, blank=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=300)

apps/screen/forms.py
from django import forms
from apps.screen.models import Prevent, Video

class PreventForm(forms.ModelForm):

    class Meta:
        model = Prevent
        fields = [
            'type',
            'item'
        ]
        labels = {
            'type':'Type',
            'item':'Item'
        }
        widgets = {
            'type' : forms.Select(attrs={'class':'form-control'}),
            'item' : forms.TextInput(attrs={'class':'form-control'})
        }

class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = [
            'type',
            'url'
        ]
        labels = {
            'type':'Type',
            'url':'Url'
        }
        widgets = {
            'type' : forms.Select(attrs={'class':'form-control'}),
            'url' : forms.TextInput(attrs={'class':'form-control'})
        }

apps/screen/views.py
from django.shortcuts import render, redirect
from apps.binnacle.models import Accident, Type_Accident
from apps.screen.models import Prevent, Video
from apps.screen.forms import PreventForm, VideoForm
from django.db.models import Count
import time
from apps.user.views import Admin
# Create your views here.


def index(request):
    data = {}
    data['admin'] = Admin(request)
    data['screencast'] = 'active'
    current = Current()
    id_=current['id']

    if id_ == 0:
        current = Current_day()
        id_=current['id']
    if id_ == 0:
        current = Current_mes()
        id_=current['id']

    data['type']= Type_Accident.objects.get(id=id_)
    if Video.objects.filter(type=id_):
        data['video']= Video.objects.get(type=id_)

    data['prevent']= Prevent.objects.filter(type=id_)

    return render(request, 'screen/index.html', data)

def dia(value):
    dia = {1: 'Lunes',
           2: 'Martes',
           3: 'Miercoles',
           4: 'Jueves',
           5: 'Viernes',
           6: 'Sabado',
           7: 'Domingo'}
    return dia[value]

def Current():
    filter_one = {}
    now_day = time.strftime("%w")
    now_hour = time.strftime("%H")
    filter_one['total'] =0
    filter_one['id'] = 0
    for types in Type_Accident.objects.all().order_by('id'):
        model = Accident.objects.filter(type=types.id)
        cont = 0
        for llo in model:
            day = llo.date.strftime("%w")
            hour = llo.hour.strftime("%H")
            print(day+'-'+hour)
            if now_day == day and now_hour == hour:
                cont = cont+1
            if cont > filter_one['total']:
                filter_one['total']=cont
                filter_one['title']= llo.type.title
                filter_one['id']= llo.type.id
    print(filter_one)
    print('...')
    return filter_one


def Current_day():
    filter_one = {}
    now_day = time.strftime("%w")
    filter_one['total'] =0

    filter_one['id'] = 0
    for types in Type_Accident.objects.all().order_by('id'):
        model = Accident.objects.filter(type=types.id)
        cont = 0
        for llo in model:
            day = llo.date.strftime("%w")
            if now_day == day:
                cont = cont+1
            if cont > filter_one['total']:
                filter_one['total']=cont
                filter_one['title']= llo.type.title
                filter_one['id']= llo.type.id
    return filter_one

def Current_mes():
    filter_one = {}
    now_day = time.strftime("%B")
    filter_one['total'] =0

    filter_one['id'] = 0
    for types in Type_Accident.objects.all().order_by('id'):
        model = Accident.objects.filter(type=types.id)
        cont = 0
        for llo in model:
            day = llo.date.strftime("%B")
            if now_day == day:
                cont = cont+1
            if cont > filter_one['total']:
                filter_one['total']=cont
                filter_one['title']= llo.type.title
                filter_one['id']= llo.type.id
    return filter_one

def Settings(request):
    data = {}
    data['admin'] = Admin(request)
    data['screen'] = 'active'
    data['title'] = 'Configurar pantalla'
    data['option'] = 'Configurar pantalla'
    data['type'] =Type_Accident.objects.all().order_by('id')

    return render(request, 'screen/settings.html', data)

def Prevent_(request, funct, type, id):
    data = {}
    data['admin'] = Admin(request)
    data['screen'] = 'active'
    id_int = int(id)
    data['model'] = Prevent.objects.filter(type=type)
    data['type'] = type
    if Video.objects.filter(type=type):
        data['video'] = Video.objects.get(type=type).url

    data['title'] = 'como prevenir '+ Type_Accident.objects.get(id=type).title
    if funct == 'create':
        data['form'] = PreventForm(request.POST)
        if request.method == 'POST':
            if data['form'].is_valid():
                data['form'].save()
    elif funct == 'edit':
        data['edit'] = Prevent.objects.get(id=id_int)
        if request.method == "GET":
            data['form'] = PreventForm(instance=data['edit'])
            print(data['form'])
        else:
            data['form'] = PreventForm(request.POST, instance=data['edit'])
            if data['form'].is_valid():
                data['form'].save()
            return redirect('screen:prevent', 'create', type, '0')
    elif funct == 'delete':
        Prevent.objects.get(id=id_int).delete()
        return redirect('screen:prevent', 'create', type, '0')
    return render(request, 'screen/prevent.html', data)

def Video_(request,funct, type):
    data = {}
    data['admin'] = Admin(request)
    data['screen'] = 'active'
    data['type'] = type
    data['title']= Type_Accident.objects.get(id=type).title
    if funct == 'create':
        data['form'] = VideoForm(request.POST)
        if request.method == 'POST':
            if data['form'].is_valid():
                obj = data['form'].save(commit=False)
                obj.id =1
                data['form'].save()
                return redirect('screen:prevent', 'create', type, '0')
            else:
                print(data['form'].is_valid())
                print(data['form'].errors)

    elif funct == 'edit':
        data['edit'] = Video.objects.get(type=type)
        if request.method == "GET":
            data['form'] = VideoForm(instance=data['edit'])
            print(data['form'])
        else:
            data['form'] = VideoForm(request.POST, instance=data['edit'])
            if data['form'].is_valid():
                data['form'].save()
            return redirect('screen:prevent', 'create', type, '0')
    elif funct == 'delete':
        Video.objects.get(type=type).delete()
        return redirect('screen:prevent', 'create', type, '0')
    return render(request, 'screen/video.html', data)

templates/screen/index.html
{% extends 'base/base.html' %}
{% block meta %}

    <meta http-equiv="refresh" content="1800" >
{% endblock meta %}
{% block screen %}

    <div class="row" style="padding: 1%">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header" data-background-color="blue" align="center">
                    <h2 class="title">Es momento de prevenir {{ type }}</h2>
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col-lg-8">
                            <div style="height: 400px">
                                {% if video %}
                                <iframe width="100%" height="100%" src="{{ video.url }}?listType=playlist&list=PLAYLIST_ID&version=3&loop=1&autoplay=1&rel=0&showinfo=0&controls=0&autohide=1  " frameborder="20" allowfullscreen></iframe>
                                {% else %}
                                <div style="height: 400px;background-image: url('http://marketingland.com/wp-content/ml-loads/2015/01/video-cameras-lenses-ss-1920-800x450.jpg')">

                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card-header" style="margin-top: 20px; margin-bottom: 20px" data-background-color="purple">
                                <h3 class="title">Como prevenir?</h3>
                            </div>
                             <table class="table table-hover">
                             {% if prevent %}
                                 {% for foo in prevent %}
                                 <div class="row">
                                    <div class="col-lg-1">
                                        <h4><i class="material-icons">chevron_right</i></h4>
                                    </div>
                                    <div class="col-lg-11">
                                        <h4>{{ foo.item }}</h4>
                                    </div>
                                </div>
                                 {% endfor %}
                             {% else %}

                                 <div class="row">
                                    <div class="col-lg-1">
                                        <h4><i class="material-icons">chevron_right</i></h4>
                                    </div>
                                    <div class="col-lg-11">
                                        <h4>Sin datos</h4>
                                    </div>
                                </div>
                             {% endif %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="stats">

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock screen %}
{% block js %}
{% endblock js %}

templates/screen/prevent.html
{% extends 'base/base.html' %}
{% block title %} {{ title }}{% endblock title %}
{% block content %}
<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-12" align="center">
                <h3>
                    {% if edit %}
                        Editar el {{ title }} seleccionado
                    {% else %}
                        Crear un nuevo {{ title }}</h3>
                    {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10">
                <input type="hidden"  name="type" id="id_type" value="{{ type }}" required class="form-control" placeholder="Ingrese nombre del {{ title }}"/>
                <input type="text" name="item" id="id_item" value="{{ edit.item }}" required class="form-control" placeholder="Ingrese nombre del {{ title }}"/>
            </div>
            <div class="col-lg-2">
                <button class="btn btn-primary btn-round btn-blue" type='submit'>
                    {% if edit %}
                        Editar
                    {% else %}
                        Agregar
                    {% endif %}
                </button>
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-lg-12" align="center">
            <h3>Listado de los {{ title }}</h3>
        </div>
    </div>
    <div class="row">
            <div class="col-lg-12 col-md-12">
                 <div class="card">
                    <div class="card-header hidden-xs" data-background-color="blue">
                        <div class="row " align="center" style="font-size: x-large;">
                            <a href=""> <div class="col-md-10 col-sm-2 fix-tabla">Titulo</div></a>
                            <a href=""><div class="col-md-2 col-sm-2"></div>
                            </a>
                        </div>
                    </div>
                     <div class="card-content">
                     </div>
                      {% if model %}
                          {% for datas in model %}
                                <div class="row card-footer hidden-md" align="center">
                                    <div class="col-md-10 col-sm-2 " align="left" style="padding-left: 6%; padding-right: 20px">{{ datas.item}}</div>
                                    <div class="col-md-2 col-sm-1" >
                                        <a href="{% url 'screen:prevent' 'edit' type datas.id %}" >
                                            <i class="material-icons color-blue">edit</i>
                                        <div class="ripple-container color-blue"></div></a>
                                        <a href="{% url 'screen:prevent' 'delete' type datas.id %}" >
                                            <i class="material-icons" style="color: #00acc1">clear</i>
                                        <div class="ripple-container"></div></a>
                                    </div>
                                </div>
                             {% endfor %}
                         {% else %}
                          <div class="row">
                              <div class="col-lg-12" align="center">
                                  <h3>Sin datos</h3>
                              </div>
                          </div>
                         {% endif %}

                <div class="row card-footer">
                    <a href="{{ video }}" >
                        <div class="col-lg-8" style="padding-top: 20px">
                            <i class="material-icons" >movie</i> URL: {{ video }}
                        </div>
                    </a>
                    {% if video %}
                    <div class="col-lg-2">
                        <a href="{% url 'screen:video' 'edit' type %}" class="btn btn-primary btn-round btn-blue" style="padding-top: 10px; padding-bottom: 10px;" >Editar</a>
                    </div>
                    <div class="col-lg-2">
                        <a href="{% url 'screen:video' 'delete' type %}" class="btn btn-primary btn-round btn-blue" style="padding-top: 10px; padding-bottom: 10px;" >Eliminar</a>
                    </div>
                    {% else %}
                    <div class="col-lg-4" align="center">
                        <a href="{% url 'screen:video' 'create' type %}" class="btn btn-primary btn-round btn-blue" style="padding-top: 10px; padding-bottom: 10px;" >Agregar</a>
                    </div>
                    {% endif %}
                </div>
                </div>
            </div>
        </div>
</div>


{% endblock content %}
{% block js %}

{% endblock js %}

templates/screen/settings.html
{% extends 'base/base.html' %}
{% block title %} pantalla - prevenir {% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-10 col-md-10" align="center">
            <h3>Mantenedor como prevenir</h3>
        </div>
        <div class="col-lg-2 col-md-10" align="center">
            <a href="{% url 'screen:index' %}" class="btn btn-round btn-blue">Ver pantalla</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header" data-background-color="blue" align="center">
                    <div class="row " align="center" style="font-size: x-large;">
                        <a href=""> <div class="col-lg-4 fix-tabla">Tipo de accidente</div></a>
                        <a href=""><div class="col-lg-6 fix-tabla">Descripcion</div></a>
                        <a href="{% url 'binnacle:create_value' 'type' 'create' '0' %}">
                            <div class="col-lg-2">
                                <i class="material-icons" style="font-size: xx-large" >add_circle</i>
                            </div>
                        </a>
                    </div>

                </div>
                <div class="card-content" align="center">
                {% for foo in type %}
                    <div class="row card-footer">
                        <a href="{% url 'screen:prevent' 'create' foo.id '0' %}">
                            <div class="col-lg-4"  align="left">{{ foo }}</div>
                            <div class="col-lg-6" align="left">{{ foo.detail }}</div>
                        </a>
                    <div class="col-lg-2" style="padding-left: 55px">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="material-icons color-blue" >arrow_drop_down_circle</i>
                        <div class="ripple-container"></div></a>
                        <ul class="dropdown-menu" data-background-color="blue">
                            <li><a href="{% url 'binnacle:create_value' 'type' 'edit' foo.id %}">Editar</a></li>
                            <li><a href="{% url 'screen:prevent' 'create' foo.id '0' %}">Prevenir</a></li>
                        </ul>
                    </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}
{% block js %}

{% endblock js %}

templates/screen/video.html
{% extends 'base/base.html' %}
{% block title %} {{ title }}{% endblock title %}
{% block content %}
<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-12" align="center">
                <h3>URL para video</h3>
            </div>
        </div>
    <input type="hidden"  name="type" id="id_type" value="{{ type }}" required class="form-control" />

        <div class="row">
            <div class="col-lg-10">
                <input type="text" name="url" id="id_url" value="{{ edit.url }}" required class="form-control" placeholder="Ingrese URL para video de {{ title }}"/>
            </div>
            <div class="col-lg-2">
                <button class="btn btn-primary btn-round btn-blue" type='submit'>
                    {% if edit %}
                        Editar
                    {% else %}
                        Agregar
                    {% endif %}
                </button>
            </div>
        </div>
    </form>
</div>


{% endblock content %}
{% block js %}

{% endblock js %}